In [2]:
import pandas as pd

In [4]:
data = pd.read_csv("500hits.csv",encoding="latin-1")

In [6]:
data.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [7]:
data['PLAYER'].unique()

array(['Ty Cobb', 'Stan Musial', 'Tris Speaker', 'Derek Jeter',
       'Honus Wagner', 'Carl Yastrzemski', 'Paul Molitor',
       'Eddie Collins', 'Willie Mays', 'Eddie Murray', 'Nap Lajoie',
       'George Brett', 'Paul Waner', 'Robin Yount', 'Tony Gwynn',
       'Dave Winfield', 'Craig Biggio', 'Rickey Henderson', 'Rod Carew',
       'Lou Brock', 'Wade Boggs', 'Al Kaline', 'Roberto Clemente',
       'Cap Anson', 'Sam Rice', 'Sam Crawford', 'Frank Robinson',
       'Willie Keeler', 'Jake Beckley', 'Rogers Hornsby', 'Al Simmons',
       'Zack Wheat', 'Frankie Frisch', 'Mel Ott', 'Babe Ruth',
       'Harold Baines', 'Jesse Burkett', 'Brooks Robinson',
       'Charlie Gehringer', 'George Sisler', 'Ken Griffey Jr.',
       'Andre Dawson', 'Luke Appling', 'Goose Goslin', 'Tony Perez',
       'Chipper Jones', 'Roberto Alomar', 'Lou Gehrig', 'Billy Williams',
       'Luis Aparicio', 'Fred Clarke', 'Max Carey', 'Nellie Fox',
       'George Davis', 'Harry Heilmann', 'Ted Williams', 'Jimmie Foxx',
       'Rabbit Maranville', 'Ed Delahanty', 'Vladimir Guerrero',
       'Reggie Jackson', 'Ernie Banks', 'Richie Ashburn', 'Heinie Manush',
       'Joe Morgan', 'Fred McGriff', 'David Ortiz', 'Ted Simmons',
       'Joe Medwick', 'Frank Thomas', 'Roger Connor', 'Harry Hooper',
       'Ozzie Smith', 'Lloyd Waner', 'Jim Rice', 'Red Schoendienst',
       'Pie Traynor', 'Mickey Mantle', 'Ryne Sandberg', 'Enos Slaughter',
       'Edd Roush', 'Alan Trammell', 'Carlton Fisk', 'Orlando Cepeda',
       'Billy Herman', 'Joe Torre', 'Barry Larkin', 'Jim Thome',
       'Eddie Mathews', 'Jeff Bagwell', 'Jim Bottomley', 'Bobby Wallace',
       "Jim O'rourke", 'Kirby Puckett', 'Kiki Cuyler', 'Dan Brouthers',
       'Joe Cronin', 'Hugh Duffy', 'Ron Santo', 'Bid McPhee',
       'Edgar Martinez', 'Mike Schmidt', 'Willie Stargell', 'Joe Sewell',
       'Joe Kelley', 'Joe DiMaggio', 'Willie McCovey', 'Bill Terry',
       'Pee wee Reese', 'Larry Walker', 'Billy Hamilton', 'Yogi Berra',
       'Mike Piazza', 'Duke Snider', 'John Ward', 'Arky Vaughan',
       'Gary Carter', 'Harmon Killebrew', 'George Burns', 'Scott Rolen',
       'Chuck Klein', 'George Kell', 'Johnny Bench', 'Bobby Doerr',
       'Earl Averill', 'Bill Mazeroski', 'Johnny Mize', 'Dave Bancroft',
       'Jimmy Collins', 'Sam Thompson', 'Bill Dickey', 'Minnie Minoso',
       'Gil Hodges', 'Tony Oliva', 'Gabby Hartnett', 'Earle Combs',
       'Tony Lazzeri', 'King Kelly', 'Ernie Lombardi', 'Lou Boudreau',
       'George Kelly', 'Travis Jackson', 'Elmer Flick', 'Rick Ferrell',
       'Joe Tinker', 'Hank Aaron', 'Cal Ripken', 'Omar Vizquel',
       'Iván Rodríguez', 'Johnny Damon', 'Vada Pinson', 'Al Oliver',
       'Carlos Beltran', 'Rusty Staub', 'Bill Buckner', 'Dave Parker',
       'Doc Cramer', 'Lave Cross', 'Tim Raines Sr.', 'Steve Garvey',
       'Luis Gonzalez', 'Julio Franco', 'Willie Davis', 'Steve Finley',
       'George Vanhaltren', 'Garret Anderson', 'Todd Helton',
       'Buddy Bell', 'Jimmy Ryan', 'Mickey Vernon', 'Bobby Abreu',
       'Jeff Kent', 'Bill Dahlen', 'Jimmy Rollins', 'Torii Hunter',
       'Dwight Evans', 'Mark Grace', 'Kenny Lofton', 'Stuffy McInnis',
       'Chili Davis', 'Brett Butler', 'Michael Young', 'Lou Whitaker',
       'Joe Judge', 'Paul Konerko', 'Bernie Williams', 'Andres Galarraga',
       'Edgar Renteria', 'B.J. Surhoff', 'Dave Concepcion',
       'Jake Daubert', 'Aramis Ramirez', 'Charlie Grimm', 'Gary Gaetti',
       'Tony Fernandez', 'Carlos Lee', 'Jimmy Dykes', 'Willie McGee',
       'Patsy Donovan', 'Tommy Corcoran', 'Jose Cruz', 'Marquis Grissom',
       'Bert Campaneris', 'John Olerud', 'Fred Tenney', 'Graig Nettles',
       'Darrell Evans', 'Juan Pierre', 'Joe Kuhel', 'Willie Randolph',
       'Willie Wilson', 'Jason Kendall', 'Stan Hack', 'Cecil Cooper',
       'Larry Bowa', 'Joe Carter', 'Keith Hernandez', 'Will Clark',
       'Sherry Magee', 'Dick Bartell', 'Hal Chase', 'Magglio Ordonez',
       'Don Mattingly', 'Victor Martinez', 'Ruben Sierra', 'Ed Konetchy',
       'Ken Boyer', 'Ken Griffey Sr.', 'Tommy Leach', 'Placido Polanco',
       'Dick Groat', 'Jose Reyes', 'Wally Moses', 'Don Baylor',
       'Maury Wills', 'Moises Alou', 'Buddy Myer', 'Herman Long',
       'Joe Mauer', 'Tommy Davis', 'Dale Murphy', 'Chris Chambliss',
       'Ellis Burks', "Paul O'Neill", 'Felipe Alou', 'Clyde Milan',
       'Brian Downing', 'Garry Templeton', 'Matt Holliday',
       'Alfonso Soriano', 'Harvey Kuenn', 'Hal McRae', 'Alvin Dark',
       'Cesar Cedeno', 'Tim Wallach', 'Jimmy Sheckard', 'Ed McKean',
       'Carney Lansford', 'Dixie Walker', 'Bobby Veach', 'Del Ennis',
       'Bob Elliott', 'Wally Joyner', 'Orlando Cabrera', 'Ray Durham',
       'Bob Johnson', 'Dummy Hoy', 'A.J. Pierzynski', 'Jack Glasscock',
       'Mark Grudzielanek', 'Carlos Delgado', 'Raul Ibanez', 'Lee May',
       'Brandon Phillips', 'Ken Singleton', 'Tony Phillips', 'Amos Otis',
       'Reggie Smith', 'Gary Matthews', 'Bobby Bonilla', 'Bill Madlock',
       'Tony Taylor', 'Frank White', 'Todd Zeile', 'Shawn Green',
       'Ian Kinsler', 'Del Pratt', 'Willie Horton', 'George Scott',
       'Gee Walker', 'Charlie Jamieson', 'Jeff Conine', 'Cy Williams',
       'Dusty Baker', 'George Hendrick', 'Phil Cavarretta', 'Jay Bell',
       'Melky Cabrera', 'Fred Lynn', 'Derrek Lee', 'Ben Chapman',
       'Toby Harrah', 'Tom Brown', 'Jim Edmonds', 'Steve Sax',
       'Kid Gleason', 'Pinky Higgins', 'Wally Pipp', 'Adam Jones',
       'Bing Miller', 'Devon White', 'Andruw Jones', 'Carl Crawford',
       'Don Kessinger', 'Larry Gardner', 'Bobby Lowe', 'Bill Russell',
       'Marty McManus', 'George Foster', 'Tino Martinez', 'Fielder Jones',
       'Jose Cardenal', 'Ron Fairly', 'Carl Furillo', 'Dante Bichette',
       'Jack Tobin', 'Lance Berkman', 'Royce Clayton', 'Brian Giles',
       'Terry Pendleton', 'Jim Gilliam', 'Luis Castillo', 'Larry Doyle',
       'Bobby Bonds', 'Robin Ventura', 'Claudell Washington',
       'Vinny Castilla', 'Tommy Tucker', 'Paul Hines', 'Matt Williams',
       'Roger Peckinpaugh', 'Chet Lemon', 'Ron Cey', 'Eddie Yost',
       'Bobby Murcer', 'Mark Teixeira', 'Curt Flood', 'Vern Stephens',
       'Pete Runnels', 'Dick Allen', 'Harry Davis', 'John Anderson',
       'Chuck Knoblauch', 'Bob Boone', 'Frank Baker', 'Sam West',
       'Hanley Ramirez', 'Mike Tiernan', 'Arlie Latham', 'Bobby Grich',
       'Edwin Encarnacion', 'Joe Adcock', 'Benito Santiago', 'Bob Watson',
       'Jack Clark', 'Gus Bell', 'Norm Cash', 'Babe Herman',
       'Rafael Furcal', 'Matt Kemp', 'Jack Doyle', 'Milt Stock',
       'Donie Bush', 'Kip Selbach', 'Roy White', 'Garry Maddox',
       'Curtis Granderson', 'Joe Quinn', 'Andy Pafko', 'Greg Luzinski',
       'Vernon Wells', 'Sal Bando', 'Larry Parrish', 'Mark Kotsay',
       'Lance Parrish', 'Jermaine Dye', 'Alex Rios', 'David Wright',
       'Matty Alou', 'Boog Powell', 'Travis Fryman', 'Bret Boone',
       'Frank Howard', 'Heinie Groh', 'Joe Jackson', 'Harry Stovey',
       'Frank Schulte', 'Ted Kluszewski', 'Ozzie Guillen',
       'Asdrubal Cabrera', 'Jhonny Peralta', 'Chris Speier',
       'Ginger Beaumont', 'Randy Winn', 'Johnny Callison', 'Mike Griffin',
       'Ossie Bluege', 'Kent Hrbek', 'Deacon McGuire', 'Freddy Lindstrom',
       'Howie Kendrick', 'Nomar Garciaparra', 'Eric Young Sr.',
       'Rocky Colavito', 'Tony Cuccinello', 'Albert Belle', 'Jim Fregosi',
       'Steve Brodie', 'Leo Cardenas', 'Eric Karros', 'Cy Seymour',
       'Starlin Castro', 'Cupid Childs', 'Vic Power',
       'Baby doll Jacobson', 'Mark Loretta', 'Frank McCormick',
       'Ken Caminiti', 'Augie Galan', 'Bill White', 'Bobby Thomson',
       'Lou Piniella', 'Roy Sievers', 'George A. Bell', 'Pinky Whitney',
       'Dave Philley', 'Mike Cameron', 'Aubrey Huff', 'Darin Erstad',
       'Jim Gantner', 'Lu Blue', 'Richie Hebner', 'Bob Meusel',
       'Vic Wertz', 'Billy Goodman', 'Alfredo Griffin',
       'Hardy Richardson', 'Shano Collins', 'Tony Pena', 'Joe Vosmik',
       'Dom Dimaggio', 'Pete Fox', 'Rico Carty', 'Tim Salmon',
       'Davey Lopes', 'Fred Pfeffer', 'Shin-Soo Choo', 'Reggie Sanders',
       'Jim Wynn', 'Jorge Posada', 'Brady Anderson', 'Cookie Rojas',
       'Mickey Rivers'], dtype=object)

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe =  OneHotEncoder(handle_unknown = 'ignore',sparse_output=False).set_output(transform='pandas')

In [12]:
ohetransform = ohe.fit_transform(data[['PLAYER']])

In [15]:
    ohetransform

,PLAYER_A.J. Pierzynski,PLAYER_Adam Jones,PLAYER_Al Kaline,PLAYER_Al Oliver,PLAYER_Al Simmons,PLAYER_Alan Trammell,PLAYER_Albert Belle,PLAYER_Alex Rios,PLAYER_Alfonso Soriano,PLAYER_Alfredo Griffin,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
461,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
462,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
data.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [17]:
ohetransform.head()

,PLAYER_A.J. Pierzynski,PLAYER_Adam Jones,PLAYER_Al Kaline,PLAYER_Al Oliver,PLAYER_Al Simmons,PLAYER_Alan Trammell,PLAYER_Albert Belle,PLAYER_Alex Rios,PLAYER_Alfonso Soriano,PLAYER_Alfredo Griffin,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
print(data.columns)

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB',
       ...
       'PLAYER_Willie Horton', 'PLAYER_Willie Keeler', 'PLAYER_Willie Mays',
       'PLAYER_Willie McCovey', 'PLAYER_Willie McGee',
       'PLAYER_Willie Randolph', 'PLAYER_Willie Stargell',
       'PLAYER_Willie Wilson', 'PLAYER_Yogi Berra', 'PLAYER_Zack Wheat'],
      dtype='object', length=478)

In [36]:
data = pd.concat([data, ohetransform], axis=1).drop(columns=['PLAYER'], errors='ignore')

In [37]:
data.head(10)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,24,3035,11434,2246,4189,724,295,117,726,1249,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,22,3026,10972,1949,3630,725,177,475,1951,1599,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,22,2789,10195,1882,3514,792,222,117,724,1381,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20,2747,11195,1923,3465,544,66,260,1311,1082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21,2792,10430,1736,3430,640,252,101,0,963,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,23,3308,11988,1816,3419,646,59,452,1844,1845,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,21,2683,10835,1782,3319,605,114,234,1307,1094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,25,2826,9949,1821,3315,438,187,47,520,1499,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,22,2992,10881,2062,3283,523,140,660,1903,1464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,21,3026,11336,1627,3255,560,35,504,1917,1333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0